-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-03-04 03:08:34 GMT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ACCESS_LOG 
    ( 
     access_id        VARCHAR2 (10)  NOT NULL , 
     member_id        VARCHAR2 (10)  NOT NULL , 
     booking_id       VARCHAR2 (10)  NOT NULL , 
     access_time      TIMESTAMP WITH LOCAL TIME ZONE  NOT NULL , 
     access_result    VARCHAR2 (10)  NOT NULL , 
     door_location    VARCHAR2 (10)  NOT NULL , 
     MEMBER_member_id VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE ACCESS_LOG 
    ADD CONSTRAINT ACCESS_LOG_PK PRIMARY KEY ( access_id ) ;

CREATE TABLE BOOKING 
    ( 
     booking_id       VARCHAR2 (20)  NOT NULL , 
     member_id        VARCHAR2 (20)  NOT NULL , 
     room_id          VARCHAR2 (20)  NOT NULL , 
     start_time       TIMESTAMP WITH LOCAL TIME ZONE  NOT NULL , 
     end_time         TIMESTAMP WITH LOCAL TIME ZONE  NOT NULL , 
     booking_status   VARCHAR2 (20)  NOT NULL , 
     created_at       TIMESTAMP WITH LOCAL TIME ZONE  NOT NULL , 
     payment_amount   VARCHAR2 (20)  NOT NULL , 
     payment_method   VARCHAR2 (20)  NOT NULL , 
     payment_status   VARCHAR2 (20)  NOT NULL , 
     paid_at          TIMESTAMP WITH LOCAL TIME ZONE  NOT NULL , 
     ROOM_room_id     VARCHAR2 (20)  NOT NULL , 
     MEMBER_member_id VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_PK PRIMARY KEY ( booking_id ) ;

CREATE TABLE MEMBER 
    ( 
     member_id    VARCHAR2 (20)  NOT NULL , 
     plan_id      VARCHAR2 (10)  NOT NULL , 
     full_name    VARCHAR2 (20)  NOT NULL , 
     email        VARCHAR2 (20)  NOT NULL , 
     phone        VARCHAR2 (20)  NOT NULL , 
     status       VARCHAR2 (20)  NOT NULL , 
     join_date    DATE  NOT NULL , 
     PLAN_plan_id VARCHAR2 (10)  NOT NULL 
    ) 
;

ALTER TABLE MEMBER 
    ADD CONSTRAINT MEMBER_PK PRIMARY KEY ( member_id ) ;

ALTER TABLE MEMBER 
    ADD CONSTRAINT MEMBER_email_UN UNIQUE ( email ) ;

CREATE TABLE PLAN 
    ( 
     plan_id                VARCHAR2 (10)  NOT NULL , 
     plan_name              VARCHAR2 (10)  NOT NULL , 
     monthly_fee            VARCHAR2 (12)  NOT NULL , 
     max_monthly_room_hours VARCHAR2 (12)  NOT NULL 
    ) 
;

ALTER TABLE PLAN 
    ADD CONSTRAINT PLAN_PK PRIMARY KEY ( plan_id ) ;

ALTER TABLE PLAN 
    ADD CONSTRAINT PLAN_plan_name_UN UNIQUE ( plan_name ) ;

CREATE TABLE ROOM 
    ( 
     room_id     VARCHAR2 (20)  NOT NULL , 
     room_name   VARCHAR2 (20)  NOT NULL , 
     room_type   VARCHAR2 (20)  NOT NULL , 
     capacity    VARCHAR2 (20)  NOT NULL , 
     hourly_rate VARCHAR2 (20)  NOT NULL , 
     is_active   VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE ROOM 
    ADD CONSTRAINT ROOM_PK PRIMARY KEY ( room_id ) ;

ALTER TABLE ROOM 
    ADD CONSTRAINT ROOM_room_name_UN UNIQUE ( room_name ) ;

ALTER TABLE ACCESS_LOG 
    ADD CONSTRAINT ACCESS_LOG_MEMBER_FK FOREIGN KEY 
    ( 
     MEMBER_member_id
    ) 
    REFERENCES MEMBER 
    ( 
     member_id
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_MEMBER_FK FOREIGN KEY 
    ( 
     MEMBER_member_id
    ) 
    REFERENCES MEMBER 
    ( 
     member_id
    ) 
;

ALTER TABLE BOOKING 
    ADD CONSTRAINT BOOKING_ROOM_FK FOREIGN KEY 
    ( 
     ROOM_room_id
    ) 
    REFERENCES ROOM 
    ( 
     room_id
    ) 
;

ALTER TABLE MEMBER 
    ADD CONSTRAINT MEMBER_PLAN_FK FOREIGN KEY 
    ( 
     PLAN_plan_id
    ) 
    REFERENCES PLAN 
    ( 
     plan_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
